# Enable bundle for Assetic and GradientzTwigExpressBundle use
assetic:
    bundles: [ GradientzTwigExpressBundle ]

# (Optional) Add to Twig global variables, using a namespace to avoid collisions
# (especially if you have more than one bundle with 'static' views).
twig:
    globals:
        gradientz_twig_express:
            test: 'It works.'
