kaliop_twig_express_root:
    path: "/%twig_express.url_base%/"
    defaults:
        _controller: KaliopTwigExpressBundle:Static:root

kaliop_twig_express_find:
    path: "/%twig_express.url_base%/{slug}{path}"
    defaults:
        _controller: KaliopTwigExpressBundle:Static:find
    requirements:
        slug: "[A-Za-z0-9_-]+"
        path: "(\\/?[\\/\\.A-Za-z0-9_-]+)?"
