gradientz_twig_express_root:
    path: "/static/"
    defaults:
        _controller: GradientzTwigExpressBundle:Static:root

gradientz_twig_express_find:
    path: "/static/{bundle}{path}"
    defaults:
        _controller: GradientzTwigExpressBundle:Static:find
    requirements:
        bundle: "[A-Za-z0-9_]+"
        path: "(\\/?[\\/\\.A-Za-z0-9_-]+)?"
