gradientz_twig_express_root:
    path: "/%twig_express.base_url%/"
    defaults:
        _controller: GradientzTwigExpressBundle:Static:root

gradientz_twig_express_find:
    path: "/%twig_express.base_url%/{slug}{path}"
    defaults:
        _controller: GradientzTwigExpressBundle:Static:find
    requirements:
        slug: "[A-Za-z0-9_-]+"
        path: "(\\/?[\\/\\.A-Za-z0-9_-]+)?"
