# REQUIRED: enable this bundle to be used with KaliopTwigExpressBundle
twig_express:
    bundles:
        -   name: KaliopTwigExpressBundle
            slug: twig-express-test
            root: Resources/test

# (Optional) Add to Twig global variables, using a namespace to avoid collisions
# (especially if you have more than one bundle with 'static' views).
twig:
    globals:
        twig_express_demo:
            test: 'It works.'
